services:
  template-nginx:
    container_name: template-nginx
    image: nginx:alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/config/nginx/conf.d/api.conf:/etc/nginx/conf.d/api.conf
      - ./docker/config/nginx/conf.d/console.conf:/etc/nginx/conf.d/console.conf
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - default-network

  template-php:
    container_name: template-php
    build:
      context: .
      dockerfile: Dockerfile.php.dev
    restart: always
    working_dir: /var/www
    command: >
      sh -c "
      php artisan migrate --force &&
      php artisan queue:work --sleep=3 --tries=3 &
      exec php-fpm
      "
    ports:
      - "9000:9000"
    volumes:
      - ./template-api/:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    depends_on:
      - template-nginx
    networks:
      - default-network

volumes:
  nginx-data:

networks:
  default-network:
    driver: bridge
